name: Deploy to Google Cloud Storage

on:
  push:
    paths:
      - 'data/json/**'
    branches:
      - main
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
    
        - name: Setup GCP
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}
        
        - name: Decode GCP Service Account Key
          run: |
            echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > temp-sa.json
        
        - name: Authenticate with gcloud using temp-sa.json
          run: |
            gcloud auth activate-service-account --key-file=temp-sa.json

        - name: Upload JSON data to GCS
          run: |
            gsutil -m rsync -r -d data/json/ ${{ secrets.GCS_BUCKET_PATH }}

        - name: Post Processing
          run : |
            rm -f temp-sa.json
